apiVersion: v1
kind: Service
metadata:
  name: odk-central-service
  labels:
    {{- include "odk-central.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendport }}
      targetPort: {{ .Values.service.frontendport }}
      protocol: TCP
      name: http
  selector:
    {{- include "odk-central.selectorLabels" . | nindent 4 }}
